# Generated by Django 2.2.10 on 2020-11-13 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=20, verbose_name='Last Name')),
                ('computingID', models.CharField(max_length=8, verbose_name='Computing ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone Number')),
                ('zoomID', models.CharField(max_length=11, verbose_name='Personal Zoom ID')),
                ('graduationYear', models.IntegerField(null=True, verbose_name='Graduation Year')),
                ('bio', models.CharField(max_length=4000, verbose_name='Bio')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=4)),
                ('number', models.IntegerField()),
                ('preferredSize', multiselectfield.db.fields.MultiSelectField(choices=[('2_people', '2 people total'), ('3_people', '3 people total'), ('4-5_people', '4-5 people total'), ('6_people', '6+ people')], max_length=37)),
                ('preferredFrequency', multiselectfield.db.fields.MultiSelectField(choices=[('daily', '4-6 times a week'), ('semidaily', '2-3 times a week'), ('weekly', 'Weekly'), ('biweekly', 'Once every two weeks'), ('before_exams', 'Only before exams')], max_length=44)),
                ('preferredTimeOfDay', multiselectfield.db.fields.MultiSelectField(choices=[('early_morning', 'Early mornings (6AM-9AM ET)'), ('mid_morning', 'Mid-morning (9AM-12PM ET)'), ('early_afternoon', 'Early afternoon (12PM-3PM ET)'), ('late_afternoon', 'Late afternoon (3PM-6PM)'), ('evening', 'Evening (6PM-9PM)'), ('night', 'Night (9PM-12AM)')], max_length=70)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_courses', to='study_buddy.Student')),
            ],
            options={
                'unique_together': {('student', 'prefix', 'number')},
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(default='', max_length=30, verbose_name='Course Name')),
                ('groupName', models.CharField(default='', max_length=100, verbose_name='Group Name')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_owner', to='study_buddy.Student', verbose_name='Owner')),
                ('studentCourse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study_buddy.StudentCourse', verbose_name='Course')),
                ('students', models.ManyToManyField(to='study_buddy.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(related_name='students', to='study_buddy.Student')),
            ],
        ),
    ]
