# Generated by Django 3.1.1 on 2020-10-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.CharField(max_length=4000, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='student',
            name='computingID',
            field=models.CharField(max_length=8, verbose_name='Computing ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstName',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduationYear',
            field=models.IntegerField(null=True, verbose_name='Graduation Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastName',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zoomID',
            field=models.CharField(max_length=11, verbose_name='Personal Zoom ID'),
        ),
    ]
