# Generated by Django 3.1.1 on 2020-11-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('operation', models.CharField(max_length=10, verbose_name='Operation')),
                ('viewed', models.BooleanField(default=False)),
                ('studentNum', models.CharField(max_length=10, null=True)),
                ('groupNum', models.CharField(max_length=10, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study_buddy.student', verbose_name='Student')),
            ],
        ),
    ]
