# Generated by Django 3.1.1 on 2020-10-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0002_auto_20201023_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
