# Generated by Django 2.2.10 on 2020-11-24 03:13

from django.db import migrations
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='preferredFrequency',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('daily', ' 4-6 times a week'), ('semidaily', ' 2-3 times a week'), ('weekly', ' Weekly'), ('biweekly', ' Every two weeks'), ('before_exams', ' Before exams')], max_length=44, verbose_name='Preferred Frequency'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='preferredSize',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('2_people', ' 2 people total'), ('3_people', ' 3 people total'), ('4-5_people', ' 4-5 people total'), ('6_people', ' 6+ people')], max_length=37, verbose_name='Preferred Size'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='preferredTimeOfDay',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('early_morning', ' 6AM-9AM'), ('mid_morning', ' 9AM-12PM'), ('early_afternoon', ' 12PM-3PM'), ('late_afternoon', ' 3PM-6PM'), ('evening', ' 6PM-9PM'), ('night', ' 9PM-12AM')], max_length=70, verbose_name='Preferred Time'),
        ),
    ]
