# Generated by Django 2.2.10 on 2020-11-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0003_auto_20201105_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=6)),
                ('students', models.ManyToManyField(related_name='students_in_group', to='study_buddy.Student')),
            ],
        ),
    ]
