# Generated by Django 2.2.10 on 2020-11-24 03:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0003_auto_20201123_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='computingID',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Invalid computing ID', regex='[a-z][a-z][a-z]?[0-9][a-z][a-z][a-z]?')], verbose_name='Computing ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduationYear',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2028)], verbose_name='Graduation Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zoomID',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='Personal Zoom ID'),
        ),
    ]
