# Generated by Django 2.2.10 on 2020-11-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0004_studygroup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('student', 'prefix', 'number')},
        ),
    ]
