# Generated by Django 2.2.10 on 2020-11-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0005_auto_20201105_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='groupName',
            field=models.CharField(max_length=40, null=True, verbose_name='Group Name'),
        ),
    ]
