# Generated by Django 3.1.1 on 2020-11-10 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0007_auto_20201110_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_students', to='study_buddy.studygroup'),
        ),
    ]
