# Generated by Django 3.1.1 on 2020-11-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0008_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='student',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='students',
            field=models.ManyToManyField(to='study_buddy.Student'),
        ),
    ]
