# Generated by Django 3.1.1 on 2020-11-13 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0009_auto_20201110_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_owner', to='study_buddy.student', verbose_name='Owner'),
        ),
    ]
