# Generated by Django 3.1.1 on 2020-11-13 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0010_studygroup_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_owner', to='study_buddy.student', verbose_name='Owner'),
        ),
    ]
